### ISSUE TITLE
Golden Rectangle GDL/visualization mismatch

### ISSUE THREAD

**Issue by AlexLandau** [ggp-org/ggp-repository#29]
The Golden Rectangle game description has eight rows (0 through 7), but the visualization only shows seven (0 through 6). This should be resolved one way or the other.

Games usually don't last long enough for the error to be apparent.

**Comment by AlexLandau** [comment]
Sample match where this happened: http://www.ggp.org/view/tiltyard/matches/0fb1a5f765509d6f93c006e4978771d6ebbb5ebf/

**Comment by samschreiber** [comment]
We should update the visualization.

**Comment by AlexLandau** [comment]
Fixed by #30.
